version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
  proxy:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf